version: '3'
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: test
      PMA_PASSWORD: test
    ports:
      - 3000:80

  smtp:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
    depends_on:
      - php
